In [35]:
import pandas as pd

In [36]:
import numpy as np

In [37]:
import cv2

In [38]:
#read an image

img1=cv2.imread("img/fruits.png")

In [39]:
print(type(img1))

<class 'numpy.ndarray'>


In [40]:
print(img1.shape)

(512, 512, 3)


In [41]:
print(img1)

[[[225 188 245]
  [224 187 244]
  [223 185 245]
  ...
  [128 135 164]
  [128 134 163]
  [128 134 163]]

 [[232 199 243]
  [231 197 244]
  [229 194 245]
  ...
  [128 135 164]
  [128 134 163]
  [127 134 163]]

 [[238 206 243]
  [238 205 242]
  [238 204 244]
  ...
  [128 134 163]
  [128 134 163]
  [128 134 163]]

 ...

 [[170 183 217]
  [172 184 217]
  [177 186 217]
  ...
  [153 158 183]
  [157 163 188]
  [160 168 193]]

 [[171 184 218]
  [171 183 217]
  [174 184 218]
  ...
  [156 160 185]
  [154 156 186]
  [154 159 186]]

 [[174 186 220]
  [171 184 218]
  [172 182 216]
  ...
  [166 167 190]
  [158 158 185]
  [149 155 182]]]


In [42]:
img2=cv2.imread("img/moon.png")

In [43]:
print(img2.shape)

(512, 512, 3)


In [44]:
cv2.imshow("window",img2)
cv2.waitKey(100)

-1

# converting rgb image into gray scale image

In [45]:
img_gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
cv2.imshow("window",img_gray)


In [46]:
cv2.waitKey(1)

-1

In [47]:
print(img_gray.shape)

(512, 512)


# playing with rgb

In [48]:
#Yellow
img1[:,:,0]=0
cv2.imshow("window",img1)
cv2.waitKey(100)


-1

In [49]:
#red
img1[:,:,1]=0
cv2.imshow("window",img1)
cv2.waitKey(100)


-1

# 3 in one

In [50]:
img1=cv2.imread("img/fruits.png")
imgblue=img1[:,:,0]
imggreen=img1[:,:,1]
imgred=img1[:,:,2]

new_img=np.hstack((imgblue,imggreen,imgred))

cv2.imshow("window",new_img)
cv2.waitKey(1000)


-1

In [51]:
print(new_img.shape)

(512, 1536)


# resize the images

In [52]:
#resize image using opencv
img1=cv2.imread("img/fruits.png")
img_resize=cv2.resize(img1,(256,256))
cv2.imshow("window",img_resize)
cv2.waitKey(1000)



-1

In [53]:
print(img_resize.shape)

(256, 256, 3)


In [54]:
#resize image using opencv
img1=cv2.imread("img/fruits.png")
img_resize=cv2.resize(img1,(800,800))
cv2.imshow("window",img_resize)
cv2.waitKey(1000)



-1

In [55]:
print(img_resize.shape)

(800, 800, 3)


In [56]:
#resize image using opencv
img1=cv2.imread("img/fruits.png")
img_resize=cv2.resize(img1,(512,512))
cv2.imshow("window",img_resize)
cv2.waitKey(1000)


-1

In [57]:
print(img_resize.shape)

(512, 512, 3)


# Flipping an image

In [58]:
#flipping an image

#180 degree

img1=cv2.imread("img/fruits.png")
img_flip=cv2.flip(img1,0)
cv2.imshow("window",img_flip)
cv2.waitKey(1000)

-1

In [59]:
#horizontal shift
#used in data augmentation in image reading process while trainig an ml model (eg : all the dogs are looking at lefft side , so to eliminate overfitting we use horizontal shift to make dog look right side also) 

img1=cv2.imread("img/fruits.png")
img_flip=cv2.flip(img1,1)
cv2.imshow("window",img_flip)
cv2.waitKey(1000)

-1

In [60]:
#flipping in horizontal and then vertical 
img1=cv2.imread("img/fruits.png")
img_flip=cv2.flip(img1,-1)
cv2.imshow("window",img_flip)
cv2.waitKey(1000)

-1

# image cropping

In [61]:
#image cropping

#syntax{ img1[height,width] }

img1=cv2.imread("img/fruits.png")
img_crop=img1[100:300,200:500]
cv2.imshow("cropped",img_crop)
cv2.waitKey(1000)


-1

In [62]:
#image cropped from top left (fetching from origin)
img1=cv2.imread("img/fruits.png")
img_crop=img1[0:300,0:500]
cv2.imshow("cropped",img_crop)
cv2.waitKey(1000)


-1

# Saving an image

In [63]:
cv2.imwrite('fruits_cropped.png',img_crop)

True

# Drawing shapes

In [74]:
# read an image
image=np.zeros((512,512,3))
cv2.imshow('window',image)
cv2.waitKey(1000)

-1

In [75]:
#creating a shape

#1 rectangle

cv2.rectangle(image,pt1=(100,100),pt2=(300,300),color=(255,0,0),thickness=3)
cv2.imshow('window',image)
cv2.waitKey(1000)

-1

In [76]:
#2 Circle

cv2.circle(image,center=(100,400),radius=50,color=(0,0,255),thickness=3)
cv2.imshow('window',image)
cv2.waitKey(1000)

-1

In [77]:
#3 line

cv2.line(image,pt1=(0,0),pt2=(512,512),thickness=2,color=(0,255,0))
cv2.imshow('window',image)
cv2.waitKey(1000)

-1

In [78]:
#4 Text
cv2.putText(image,org=(100,100),fontScale=4,color=(0,255,255),thickness=2,lineType=cv2.LINE_AA,text="Hello",fontFace=cv2.FONT_ITALIC)
cv2.imshow('window',image)
cv2.waitKey(1000)

-1

# Live Direct drawing

In [ ]:
#interacting with an image
# 0xFF ==ord('x')----> pressing 'x' on keyboard will break the infinite while loop
# used while working with videos   

img3=np.zeros((512,512,3))

while True:
    cv2.imshow('window',img3)

    if cv2.waitKey(1) & 0xFF ==ord('x'):
        break

cv2.destroyAllWindows()

In [ ]:
#event==0 is mouse moved
#event==1 is mouse down clicked
#event==4 is mouse up clicked
#when we click anywhere (x,y) on the image the shape should print.



def draw(event,x,y,flags,params):
    if event==1:
        cv2.circle(img3,center=(x,y),radius=50,color=(0,255,0),thickness=2)
    
    
cv2.namedWindow(winname="window")
cv2.setMouseCallback("window",draw)


img3=np.zeros((512,512,3))

while True:
    cv2.imshow('window',img3)

    if cv2.waitKey(1) & 0xFF ==ord('x'):
        break

cv2.destroyAllWindows()

In [ ]:
#creating shape on dargging the mouse on image
#events involed are click , drag(move) , leave
#creating shape when mouse is dragged , not when clicked 


flag=False
ix=-1
iy=-1

def draw1(event,x,y,flags,params):

    global flag,ix,iy

    if event==1:

        flag=False
        ix=x
        iy=y

    elif event==0:
        flag==True
        cv2.rectangle(img3,pt1=(ix,iy),pt2=(x,y),color=(255,0,255),thickness=-1)
    
    elif event==4:
        if flag == False:
            cv2.rectangle(img3,pt1=(ix,iy),pt2=(x,y),color=(255,0,255),thickness=-1)


cv2.namedWindow(winname="window")
cv2.setMouseCallback("window",draw1)


img3=np.zeros((512,512,3))

while True:
    cv2.imshow('window',img3)

    if cv2.waitKey(1) & 0xFF ==ord('x'):
        break

cv2.destroyAllWindows()